name: CI/CD

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

jobs:
  makeitso:

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/osgeo/gdal:ubuntu-full-latest

    steps:
      - uses: actions/checkout@v3

      - name: Hello GDAL/OGR 
        run: |
          ogr2ogr --help

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
